//! Task completion is distinct from finishing the response stream.
use serde_json::Value;

#[derive(Default)]
pub(super) struct TaskOutcome {
    accepted_done: Option<bool>,
    finalized: Option<bool>,
}

impl TaskOutcome {
    pub(super) fn accept_done(&mut self, remaining: &[String]) {
        self.accepted_done = Some(remaining.is_empty());
    }

    /// Call only for a summary generated by the runtime's validated finalizer.
    pub(super) fn finalized(&mut self, summary: &str) {
        self.finalized = Some(
            !summary
                .lines()
                .any(|line| line.trim_start().starts_with("- remaining:")),
        );
    }

    /// Each pair records whether a runtime goal was requested and actually passed.
    pub(super) fn verified_goal_checks(&mut self, goals: &[(bool, bool)]) {
        self.finalized = Some(
            goals.iter().any(|(requested, _)| *requested)
                && goals
                    .iter()
                    .all(|(requested, passed)| !requested || *passed),
        );
    }

    pub(super) fn completed(&self, messages: &[Value]) -> bool {
        if super::recovery_focus::RecoveryFocus::from_messages(messages, None, None).is_pending() {
            return false;
        }
        let terminal = messages
            .iter()
            .rev()
            .find(|message| message["role"].as_str() == Some("assistant"));
        let remaining = terminal
            .and_then(|message| message["content"].as_str())
            .is_some_and(|text| {
                text.lines()
                    .any(|line| line.trim_start().starts_with("- remaining:"))
            });
        // Governor state and transport completion are diagnostic state, not proof.
        self.accepted_done.or(self.finalized).unwrap_or(false) && !remaining
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn stream_end_at_iteration_cap_is_not_completion() {
        let messages =
            vec![json!({"role":"assistant","content":"Found src/main.rs, still investigating."})];
        assert!(!TaskOutcome::default().completed(&messages));
    }

    #[test]
    fn raw_done_at_iteration_cap_has_no_completion_authority() {
        // The no-tool fallthrough may set AgentState::Done at the last iteration.
        // That state is deliberately not an input to the completion decision.
        for content in ["Tests still need to run.", "[DONE] Everything is complete."] {
            let messages = vec![json!({"role":"assistant","content":content})];
            assert!(!TaskOutcome::default().completed(&messages));
        }
    }

    #[test]
    fn accepted_done_with_pending_acceptance_is_incomplete() {
        let mut outcome = TaskOutcome::default();
        outcome.accept_done(&["tests still failing".to_string()]);
        assert!(!outcome.completed(&[]));
        outcome.accept_done(&[]);
        assert!(outcome.completed(&[]));
    }

    #[test]
    fn validated_finalizer_can_finish_after_the_last_iteration() {
        let mut outcome = TaskOutcome::default();
        outcome.finalized("[DONE]\nAcceptance:\n- done: tests pass");
        assert!(outcome.completed(&[
            json!({"role":"assistant","content":"[DONE]\nAcceptance:\n- done: tests pass"})
        ]));
        assert!(!outcome.completed(&[
            json!({"role":"assistant","content":"[DONE]\nAcceptance:\n- remaining: tests"})
        ]));
    }

    #[test]
    fn goal_checks_require_every_requested_goal_to_pass() {
        let mut outcome = TaskOutcome::default();
        outcome.verified_goal_checks(&[(true, false), (true, true)]);
        assert!(!outcome.completed(&[]));
        outcome.verified_goal_checks(&[(false, false)]);
        assert!(!outcome.completed(&[]));
        outcome.verified_goal_checks(&[(true, true), (false, false)]);
        assert!(outcome.completed(&[]));
    }
}
